### ISSUE TITLE
Containerize the application

### ISSUE THREAD

**Issue by vaniusrb** [VS-Microservices-Academy/service-product#1]
To containerize the application we can use two approaches.
The first one could be, after an external build, just copy the binary to be executed in the container, something like this:
```
FROM alpine
COPY docker-program /bin/docker-program
CMD ["/bin/docker-program"]
```

The second option is execute the app build on the container build, using an image that contains the Rust compiler. Similar like this:

```
FROM rust:1.31
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path .
CMD ["myapp"]
```

Regardless of choice, we should change the docker-compose file to contain this container and communicate with the database.

**Comment by gustavosimon** [comment]
t

**Comment by gustavosimon** [comment]
t

**Comment by gustavosimon** [comment]
t

**Comment by gustavosimon** [comment]
teste
