### ISSUE TITLE
Add license to the repository

### ISSUE THREAD

**Issue by vaniusrb** [VS-Microservices-Academy/service-product#9]
I think of some very permissive license like MIT / Apache 2.0.

See [github doc](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by gustavosimon** [comment]
Yes, I think that we can add the MIT license to turn repository formally open-source.

**Comment by vaniusrb** [comment]
Issue fixed by PR #11
